In [ ]:
['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [16]:
categories = [
    'sci.space',
    'rec.autos',
    'rec.sport.hockey',
     'sci.med',
    'soc.religion.christian'
]

In [178]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from utility import preprocess_text
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans

(data, target) = fetch_20newsgroups(subset='train',categories= categories, return_X_y=True)

In [18]:
type(newsgroups_train)

sklearn.utils._bunch.Bunch

In [19]:
len(data)

2980

In [210]:
def preprocess(text):
    text = re.sub('From:.*\n?', '',text )
    text = re.sub('Lines:.*\n?', '',text )
    text = re.sub('Keywords:.*\n?', '',text )
    text = re.sub('Article-I.D.:.*\n?', '',text )
    text = re.sub('Distribution:.*\n?', '',text )
    text = re.sub('Reply-To:.*\n?', '',text )
    text = re.sub('Subject: ', '',text )
    text = re.sub(r'--\n.*', '', text,re.DOTALL)
    return text

In [211]:
import re
data_preprocess = []
for news in data:
    text = preprocess(news)
    text = preprocess_text(text)
    data_preprocess.append(text)

/Users/m.alaudeen/Documents/Inceptez/Git/GoogletoChatgpt/03. Building Document Similarity Engine/utility.py:16: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  text = BeautifulSoup(text, "html.parser").get_text()

In [212]:
data_news = pd.DataFrame(data_preprocess, columns=['preprocess_news'])

In [213]:
data_news['target'] = target

In [214]:
data_news['News']= data

In [215]:
data_news

,preprocess_news,target,News
0,right messiah article 2262genevarutgersedu des...,4,From: will@futon.webo.dg.com (Will Taber)\nSub...
1,space food stick organization university calif...,3,From: ghelf@violet.berkeley.edu (;;;;RD48)\nSu...
2,help mercury capri query organization univ sou...,0,From: sgs1679@ucs.usl.edu (Sudhindranath Sira ...
3,refusing divine peace alive prayer question ma...,4,From: maridai@comm.mot.com (Marida Ignacio)\nS...
4,post polio syndrome information needed please ...,2,From: jim.zisfein@factory.com (Jim Zisfein) \n...
...,...,...,...
2975,satan kicked heaven biblical organization univ...,4,From: noye@midway.uchicago.edu (vera shanti no...
2976,barbecued food health risk organization syllab...,2,From: kiran@village.com (Kiran Wagle)\nSubject...
2977,comet temporary orbit around jupiter organizat...,3,From: jscotti@lpl.arizona.edu (Jim Scotti)\nSu...
2978,saturn puzzled pricing organization washington...,0,From: mps1@cec1.wustl.edu (Mihir Pramod Shah)\...
2979,mind machine summary mind machine work organiz...,2,From: homer@tripos.com (Webster Homer)\nSubjec...

In [216]:
data_news['preprocess_news']

0       right messiah article 2262genevarutgersedu des...
1       space food stick organization university calif...
2       help mercury capri query organization univ sou...
3       refusing divine peace alive prayer question ma...
4       post polio syndrome information needed please ...
                              ...
2975    satan kicked heaven biblical organization univ...
2976    barbecued food health risk organization syllab...
2977    comet temporary orbit around jupiter organizat...
2978    saturn puzzled pricing organization washington...
2979    mind machine summary mind machine work organiz...
Name: preprocess_news, Length: 2980, dtype: object

In [217]:
tf = TfidfVectorizer(ngram_range=(1, 2),max_df=1.0, min_df=2, stop_words='english', max_features=100000 )

In [218]:
tf_matrix = tf.fit_transform(data_news['preprocess_news']).toarray()

In [219]:
actual_columns = tf.get_feature_names_out()

In [220]:
modified_columns = pd.DataFrame(tf_matrix, columns = tf.get_feature_names_out()).columns

In [221]:
tf_df = pd.DataFrame(tf_matrix, columns = tf.get_feature_names_out())

In [222]:
tf_df.shape

(2980, 78119)

In [223]:
doc_sim_df = pd.DataFrame(cosine_similarity(tf_df))

In [224]:
doc_sim_df

,0,1,2,3,4,5,6,7,8,9,...,2970,2971,2972,2973,2974,2975,2976,2977,2978,2979
0,1.000000,0.022858,0.019074,0.096019,0.004433,0.006787,0.003076,0.011156,0.001703,0.018556,...,0.019532,0.022779,0.038146,0.003356,0.016802,0.019587,0.008891,0.007645,0.016441,0.025664
1,0.022858,1.000000,0.004249,0.003539,0.000180,0.001679,0.004795,0.001931,0.001384,0.004004,...,0.013654,0.007462,0.000000,0.001821,0.040251,0.013705,0.030294,0.002465,0.002315,0.000211
2,0.019074,0.004249,1.000000,0.017083,0.000200,0.014709,0.024258,0.030702,0.006542,0.012346,...,0.004737,0.008869,0.009596,0.016560,0.011327,0.013885,0.005612,0.001606,0.054915,0.020017
3,0.096019,0.003539,0.017083,1.000000,0.006093,0.015663,0.006484,0.008322,0.004374,0.024583,...,0.005564,0.005209,0.066612,0.003550,0.010111,0.050689,0.014025,0.011527,0.016574,0.006611
4,0.004433,0.000180,0.000200,0.006093,1.000000,0.002294,0.001110,0.004938,0.006224,0.000748,...,0.001307,0.003564,0.010551,0.004277,0.000876,0.001032,0.002743,0.003182,0.001746,0.006633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2975,0.019587,0.013705,0.013885,0.050689,0.001032,0.007094,0.009113,0.005201,0.010782,0.022800,...,0.012176,0.009958,0.006007,0.006065,0.014589,1.000000,0.010272,0.005826,0.021949,0.000965
2976,0.008891,0.030294,0.005612,0.014025,0.002743,0.001949,0.009655,0.002657,0.000766,0.011822,...,0.011450,0.001614,0.015056,0.000248,0.012155,0.010272,1.000000,0.004550,0.011136,0.008396
2977,0.007645,0.002465,0.001606,0.011527,0.003182,0.010927,0.005161,0.004619,0.002181,0.001178,...,0.010389,0.002233,0.000411,0.010670,0.034620,0.005826,0.004550,1.000000,0.003208,0.003450
2978,0.016441,0.002315,0.054915,0.016574,0.001746,0.006968,0.015203,0.024266,0.003703,0.017466,...,0.003171,0.005616,0.005249,0.001389,0.007111,0.021949,0.011136,0.003208,1.000000,0.010641
2979,0.025664,0.000211,0.020017,0.006611,0.006633,0.002026,0.022416,0.029434,0.000180,0.021651,...,0.007627,0.002280,0.023959,0.004343,0.005095,0.000965,0.008396,0.003450,0.010641,1.000000

In [225]:
km = KMeans(n_clusters=5, random_state=0)
km.fit_transform(doc_sim_df)
km.labels_
cluster_labels = km.labels_
cluster_labels = pd.DataFrame(cluster_labels, columns=['ClusterLabel'])

/opt/homebrew/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [226]:
km.cluster_centers_

array([[0.01128604, 0.00515481, 0.008784  , ..., 0.00442143, 0.01056881,
        0.0052369 ],
       [0.01191501, 0.01748601, 0.01050673, ..., 0.01433986, 0.01140464,
        0.01149633],
       [0.01033986, 0.00743702, 0.01090451, ..., 0.00913902, 0.00847257,
        0.0099827 ],
       [0.01361209, 0.0054941 , 0.0426251 , ..., 0.00424429, 0.04118438,
        0.0101973 ],
       [0.0379862 , 0.00617187, 0.01331913, ..., 0.00518087, 0.01244382,
        0.01385452]])

In [181]:
result = pd.concat([data_news, cluster_labels], axis  = 1)

In [ ]:
1. LDA(Latent Dirichlet allocation) Topic Modelling
2. NMF - Non Matrix Factorization

In [205]:
news_new_data = "The solar system is amazing and our galaxy milky way is expanding and rotating. This something beyond our imagination. The sun is also rotating and it is a very smallest particle when compared to milky way galaxy"

In [229]:

text = preprocess(news_new_data)
text = preprocess_text(text)

In [230]:
text

'solar system amazing galaxy milky way expanding rotating something beyond imagination sun also rotating smallest particle compared milky way galaxy'

In [235]:
tf_new = tf.transform([text])

In [251]:
tf_df  = tf_df.reset_index().drop(columns = 'level_0')

In [252]:
tf_new_df = tf_new_df.reset_index().drop(columns = 'level_0')

In [253]:
tf_new_df = pd.DataFrame(tf_new.toarray(),columns = tf.get_feature_names_out() )

In [255]:

doc_sim_df = pd.DataFrame(cosine_similarity(pd.concat([tf_df,tf_new_df])))

In [257]:
doc_sim_df.iloc[2980,:]

0       0.007434
1       0.000000
2       0.005371
3       0.001632
4       0.000000
          ...
2976    0.000000
2977    0.000000
2978    0.000000
2979    0.000000
2980    1.000000
Name: 2980, Length: 2981, dtype: float64

In [258]:
doc_sim_df

,0,1,2,3,4,5,6,7,8,9,...,2971,2972,2973,2974,2975,2976,2977,2978,2979,2980
0,1.000000,0.022858,0.019074,0.096019,0.004433,0.006787,0.003076,0.011156,0.001703,0.018556,...,0.022779,0.038146,0.003356,0.016802,0.019587,0.008891,0.007645,0.016441,0.025664,0.007434
1,0.022858,1.000000,0.004249,0.003539,0.000180,0.001679,0.004795,0.001931,0.001384,0.004004,...,0.007462,0.000000,0.001821,0.040251,0.013705,0.030294,0.002465,0.002315,0.000211,0.000000
2,0.019074,0.004249,1.000000,0.017083,0.000200,0.014709,0.024258,0.030702,0.006542,0.012346,...,0.008869,0.009596,0.016560,0.011327,0.013885,0.005612,0.001606,0.054915,0.020017,0.005371
3,0.096019,0.003539,0.017083,1.000000,0.006093,0.015663,0.006484,0.008322,0.004374,0.024583,...,0.005209,0.066612,0.003550,0.010111,0.050689,0.014025,0.011527,0.016574,0.006611,0.001632
4,0.004433,0.000180,0.000200,0.006093,1.000000,0.002294,0.001110,0.004938,0.006224,0.000748,...,0.003564,0.010551,0.004277,0.000876,0.001032,0.002743,0.003182,0.001746,0.006633,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2976,0.008891,0.030294,0.005612,0.014025,0.002743,0.001949,0.009655,0.002657,0.000766,0.011822,...,0.001614,0.015056,0.000248,0.012155,0.010272,1.000000,0.004550,0.011136,0.008396,0.000000
2977,0.007645,0.002465,0.001606,0.011527,0.003182,0.010927,0.005161,0.004619,0.002181,0.001178,...,0.002233,0.000411,0.010670,0.034620,0.005826,0.004550,1.000000,0.003208,0.003450,0.000000
2978,0.016441,0.002315,0.054915,0.016574,0.001746,0.006968,0.015203,0.024266,0.003703,0.017466,...,0.005616,0.005249,0.001389,0.007111,0.021949,0.011136,0.003208,1.000000,0.010641,0.000000
2979,0.025664,0.000211,0.020017,0.006611,0.006633,0.002026,0.022416,0.029434,0.000180,0.021651,...,0.002280,0.023959,0.004343,0.005095,0.000965,0.008396,0.003450,0.010641,1.000000,0.000000
2980,0.007434,0.000000,0.005371,0.001632,0.000000,0.000000,0.000000,0.003990,0.000000,0.000000,...,0.000000,0.006227,0.000000,0.003982,0.009557,0.000000,0.000000,0.000000,0.000000,1.000000